import React from "react";

export default function ProductAdditionalData(props) {
    return (
        <div
            className={`text-justify mt-[15px] mb-[15px] lato-text text-[15px] leading-[23px] font-normal text-[#555555]`}>
            <p className={`mb-[15px]`}>
                <strong>Royaldivine Produce Products LLP</strong> provides {props.titleKey}. Exporters in Agartala ,Agra, Agra Rampur, Ahmedabad, Aizawl, Ajmer, Aligarh, Allahabad, Alwar, Amaravati, Ambala, Ambattur, Ambernath, Amravati, Amritsar, Aurangabad, Bangalore, Bareilly, Belgaum, Bhagalpur, Bhavnagar, Bhilai, Bhiwandi, Bhopal, Bhubaneswar, Bidhannagar, Biharsharif,Bikaner, Bilaspur, Bokaro, Chandigarh, Chennai, Chittoor, Coimbatore, Cuttack, Dahod, Davanegere, Dehradun, Delhi, Dhanbad, Dharamsala, Dindigul, Diu, Durgapur, Erode, Faridabad, Fatehpur, Gandhidham, Gandhinagar, Ghaziabad, Greater Hyderabad, Greater Mumbai, Greater Warangal, Gurgaon, Guwahati, Gwalior, Haldia, Howrah , Hubballi-Dharwad, Hyderabad, Imphal, Indore, Jabalpur, Jaipur, Jalandhar, Jammu, Jamnagar, Jamshedpur, Jhansi, Jodhpur, Junagadh, Kakinada, Kalyan-Dombivali,Kanpur, Karnal , Kavaratti, Kochi, Kohima, Kolhapur, Kolkata, Kota, Lucknow, Ludhiana, Madurai, Mehsana, Mangalore, Mangaluru, Mira-Bhayandar , Moradabad, Morbi, Mumbai, Muzaffarpur, Mysore, Nagpur, Namchi, Nasik, Navi Mumbai, NDMC, Nellore,New Delhi, New Town Kolkata, Noida, Oulgaret, Pali, Panaji, Panipat, Panvel, Pasighat, Patiala, Patna, Pimpri-Chinchwad, Port Blair, Puducherry, Pune, Raipur, Rajkot, Ranchi, Raurkela Industrial Township, Rourkela, Sagar, Salem, Satna, Secunderabad, Shaharanpur, Shillong, Siliguri, Silvassa, Solapur, Srinagar, Surat, Thane, Thanjavur, Thiruvananthapuram, Thoothukudi, Thrissur, Tiruchirapalli, Tirunelveli, Tirupur, Tumkur, Udaipur, Ujjain, Ulhasnagar, Vadodara, Vapi, Varanasi, Vasai-Virar, Vellore , Vishakhapatnam.
            </p>
            <p className={`mb-[15px]`}>
                <strong>Royaldivine Produce Products LLP</strong> is leading Supplier & Exporter of {props.titleKey} in Wagle Estate Thane , Navi Mumbai, Vashi, Powai, Gujarat, Pune, Marine Drive, Marine Lines , Colaba, Zaveri Bazar, Kalbadevi, Khetwadi, Kumbharwada, Byculla, Lower Parel, Parel, Dadar, Andheri, Juhu, Belapur CBD, Mahape, Khopoli, Kalyan , Dombivali, Ulhasnagar, Sion, Dharavi, Wadala.
            </p>
            <p>
                <strong>Royaldivine Produce Products LLP</strong> Supplier & Exporter of {props.titleKey} in
                Afghanistan, Albania ,Algeria, Andorra, Angola, Antigua and Barbuda, Argentina, Armenia, Aruba, Austria, Azerbaijan, Bahamas The, Bahrain, Bangladesh, Barbados, Belarus, Belgium, Belize, Beninm, Bhutan, Bolivia, Bosnia and Herzegovina, Botswana, Brazil, Brunei, Bulgaria, Burkina Faso, Burma, Burundi, Cambodia, Cameroon, Verde, Central African Republic, Chad, Chile, China, Colombia, Comoros, Congo, Democratic Republic of the, Congo, Republic of the, Costa Rica, Cote, Croatia, Cuba, Curacao, Cyprus, Denmark, Djibouti, Dominica, Dominican Republic, Ecuador, Egypt, El Salvador, Equatorial Guinea, Eritrea, Estonia, Ethiopia, Fiji, Finland, France, Gabon, Gambia The Georgia, Germany, Ghana, Greece, Grenada, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Holy See, Honduras, Hong Kong, Hungary, Iceland, India, Indonesia, Iran, Iraq, Ireland, Israel, Italy, Jamaica, Japan, Jordan, Kazakhstan, Kenya, Kiribati, Korea, North, Korea, South, Kosovo, Kyrgyzstan, Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg, Macau, Macedonia, Madagascar, Malawi, Malaysia, Maldives, Mali, Malta, Marshall Islands, Mauritania, Mauritius, Mexico, Micronesia, Moldova, Monaco, Mongolia, Montenegro, Morocco, Mozambique, Namibia, Nauru, Nepal, Netherlands, Netherlands Antilles, New Zealand, Nicaragua, Niger, Nigeria, North Korea, Norway, Pakistan, Palau, Palestinian Territories, Panama, Papua New Guinea, Paraguay, Peru, San Marino, Philippines, Poland, Portugal, Romania, Russia, Rwanda, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa ,Sao Tome and Principe, Saudi Arabia, Senegal, Serbia, Sierra Leone, Singapore, Sint Maarten, Slovakia, Slovenia, Solomon Islands, Somalia, South Africa, South Korea, South Sudan, Spain, Sri Lanka, Sudan, Suriname, Swaziland, Sweden, Switzerland, Syria, Taiwan, Tajikistan, Tanzania, Thailand, Timor-Leste, Togo, Tonga, Trinidad and Tobago, Tunisia, Turkey, Turkmenistan, Tuvalu, Uganda, Ukraine, United Arab Emirates, United Kingdom, Uruguay, Uzbekistan, Vanuatu, Venezuela, Vietnam, Yemen, Zambia, Zimbabwe, United Arab Emirates (UAE), Oman, Kuwait, Qatar, USA, UK, Canada, Australia, Czech Republic, Switzerland and European Countries.
            </p>
        </div>
    )
}